This is a testharness.js-based test.
Harness Error. harness_status.status = 1 , harness_status.message = 1 duplicate test name: "  offlineContext.state is equal to suspended."
PASS # AUDIT TASK RUNNER STARTED. 
PASS > [test-suspend] Test suspend() for offline context 
PASS   offlineContext = new OfflineAudioContext(1, 44100, 44100) did not throw an exception. 
PASS   offlineContext.state is equal to suspended. 
PASS   p1 = offlineContext.suspend() did not throw an exception. 
PASS   p1 instanceof Promise is true. 
PASS   p1 rejected correctly with TypeError: Failed to execute 'suspend' on 'OfflineAudioContext': 1 argument required, but only 0 present.. 
PASS < [test-suspend] All assertions passed. (total 5 assertions) 
PASS > [test-resume] Test resume() for offline context 
PASS   p2 = offlineContext.resume() did not throw an exception. 
PASS   p2 instanceof Promise is true. 
PASS   offlineContext.state is equal to suspended. 
PASS   p2 rejected correctly with InvalidStateError: cannot resume an offline context that has not started. 
PASS < [test-resume] All assertions passed. (total 4 assertions) 
PASS > [test-after-close] Test state after context closed 
PASS   p3 = offlineContext.startRendering() did not throw an exception. 
PASS   offlineContext.state is equal to closed. 
PASS   offlineContext.suspend() rejected correctly with TypeError: Failed to execute 'suspend' on 'OfflineAudioContext': 1 argument required, but only 0 present.. 
PASS   offlineContext.resume() rejected correctly with InvalidStateError: cannot resume a closed offline context. 
PASS < [test-after-close] All assertions passed. (total 4 assertions) 
PASS # AUDIT TASK RUNNER FINISHED: 3 tasks ran successfully. 
Harness: the test ran to completion.

