This is a testharness.js-based test.
PASS Calling waitUntil asynchronously throws an exception 
Harness: the test ran to completion.

